# Generated by Django 3.2.5 on 2021-07-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quizitem',
            constraint=models.UniqueConstraint(fields=('quiz', 'question'), name='unique_quiz_questions'),
        ),
        migrations.AddConstraint(
            model_name='quizitem',
            constraint=models.UniqueConstraint(fields=('quiz', 'index'), name='unique_quiz_index'),
        ),
        migrations.AddConstraint(
            model_name='quizitemanswer',
            constraint=models.UniqueConstraint(fields=('quiz_item', 'text'), name='unique_quizitem_text'),
        ),
    ]
