# Generated by Django 3.2.5 on 2021-07-26 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20210726_0704'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quizitem',
            name='unique_quiz_questions',
        ),
    ]
