# Generated by Django 3.2.5 on 2021-07-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_quizitem_unique_quiz_questions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quizitemanswer',
            name='unique_quizitem_text',
        ),
        migrations.AddConstraint(
            model_name='quizitem',
            constraint=models.UniqueConstraint(fields=('quiz', 'question'), name='unique_quiz_questions'),
        ),
    ]
