# Generated by Django 3.2.5 on 2021-07-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_quizitem_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizitem',
            name='index',
            field=models.PositiveIntegerField(),
        ),
    ]
