# Generated by Django 3.2.5 on 2021-07-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_alter_quizitem_index'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quizitem',
            name='unique_quiz_index',
        ),
        migrations.RemoveConstraint(
            model_name='quizresult',
            name='unique_quiz_score',
        ),
    ]
