# Generated by Django 3.2.5 on 2021-08-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_auto_20210729_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='published',
        ),
    ]
