# Generated by Django 3.2.5 on 2021-08-08 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_remove_quiz_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizitem',
            options={'ordering': ['index']},
        ),
    ]
