# Generated by Django 3.2.5 on 2021-08-01 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_remove_quiz_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('takes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_quizzes', to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='takes.completedquiz')),
                ('item_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizitemanswer')),
            ],
        ),
    ]
