# Generated by Django 3.2.5 on 2021-08-03 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('takes', '0002_completedquiz_completedquizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedquiz',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
