# Generated by Django 3.2.5 on 2021-08-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takes', '0003_completedquiz_created'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='completedquizanswer',
            constraint=models.UniqueConstraint(fields=('completed_quiz', 'item_answer'), name='unique_quiz_user_answer'),
        ),
    ]
