# Generated by Django 3.2.5 on 2021-07-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.TextField(default='Some description'),
            preserve_default=False,
        ),
    ]
