# Generated by Django 3.2.5 on 2021-07-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_pollitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollItemAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=65)),
                ('correct', models.BooleanField(default=False)),
                ('poll_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.pollitem')),
            ],
        ),
    ]
