# Generated by Django 3.2.5 on 2021-07-31 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0009_auto_20210729_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizRejectedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_message', to='quizzes.quiz')),
            ],
        ),
    ]
